

#pragma once

namespace mastermind
{
    enum class Keysym 
    {
        None,                   // no known key
        Backspace,
        Tab,
        Enter,
        Space,
        Key_0, 
        Key_1, 
        Key_2, 
        Key_3, 
        Key_4, 
        Key_5, 
        Key_6,
        Key_7, 
        Key_8, 
        Key_9,
        Key_A, 
        Key_B, 
        Key_C, 
        Key_D, 
        Key_E, 
        Key_F, 
        Key_G, 
        Key_H, 
        Key_I, 
        Key_J, 
        Key_K, 
        Key_L, 
        Key_M, 
        Key_N, 
        Key_O, 
        Key_P, 
        Key_Q, 
        Key_R, 
        Key_S, 
        Key_T, 
        Key_U, 
        Key_V, 
        Key_W, 
        Key_X, 
        Key_Y,
        Key_Z,
        F1, 
        F2, 
        F3, 
        F4, 
        F5, 
        F6, 
        F7, 
        F8, 
        F9,
        F10, 
        F11, 
        F12,
        Insert,
        Delete,
        Home,
        End,
        PageUp,
        PageDown,
        Left,
        Up,
        Down,
        Right,
        Escape
    }; 

} // mastermind